apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-info-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-info
  template:
    metadata:
      labels:
        app: hotel-info
    spec:
      containers:
        - name: hotel-info
          image: travism26/systems-hotel-info # Change this to your dockerhub username / image name
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: 'mongodb://hotel-info-mongo-srv:27017/hotel-info'
---
# Service cluster IP address
apiVersion: v1
kind: Service
metadata:
  name: hotel-info-srv
spec:
  selector:
    app: hotel-info
  ports:
    - name: hotel-info
      protocol: TCP
      port: 3000
      targetPort: 3000
---
# Service NodePort
# This is for local testing, how to access use: kubectl port-forward svc/hotel-info-node-port 3000:3000
apiVersion: v1
kind: Service
metadata:
  name: hotel-info-node-port
spec:
  type: NodePort
  selector:
    app: hotel-info
  ports:
    - name: hotel-info
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
