apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-info-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-info-mongo
  template:
    metadata:
      labels:
        app: hotel-info-mongo
    spec:
      containers:
        - image: mongo
          name: hotel-info-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-info-mongo-srv
spec:
  selector:
    app: hotel-info-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-info-mongo-node-port
spec:
  type: NodePort
  selector:
    app: hotel-info-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002
